language: java

sudo: required

services:
  - docker

jdk:
  - oraclejdk8

before_install:
  - docker pull alexeiled/docker-oracle-xe-11g
  - docker run -d --shm-size=1g -p 1521:1521 -p 8080:8080 alexeiled/docker-oracle-xe-11g
  - docker ps

install: true

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean verify
